version: '2'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user 
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
    expose:
      - 27017
    networks:
      - omniboard

  omniboard:
    image: vivekratnavel/omniboard:latest
    command: ["--mu", "mongodb://user:password@mongodb:27017/db?authSource=admin"]
    ports:
      - 127.0.0.1:9000:9000
    depends_on:
      - mongodb
    networks:
      - omniboard

volumes:
  mongodb_data:
    driver: local
networks:
  omniboard:
